# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: SpookBox Horror Movie Podcast
email: spookboxpodcast@outlook.com
description: "This is the website of horror movie podcast SpookBox."
subtitle: "A Horror Movie Podcast"
lang: en-us
author: Conor McKeown
copyright: "CC-BY 4.0"
baseurl: ""
url: "https://spookboxpodcast.co.uk"
twitter_username: agentialgamer
github_username:  cpmmckeown

permalink: /:year/:title.html

#Timezone
timezone: GMT

# Build settings
markdown: kramdown
